### PR TITLE
Create ScrollToTop button

### LINKED ISSUE #787: [Ticket]: Create a ScrollToTop button
### Project

Website (potterdb.com)

### Describe the ticket you want to create

For the new website it would be nice to have a scroll to top button such as we had on the [old website](https://potterdb.com/characters). 

It should be positioned in the bottom right of the page and only be visible when needed (e.g. unless you are a the top of the page).
When clicked it should smoothly move the page to the top. 
For the icon make sure to use [react-icons](https://react-icons.github.io/react-icons/). Do not use any other packages.

Please be aware to make a branch from the `new-website` branch. 
Before start working on this ticket please **leave a quick note below** so I can assign you. If you have any questions please ping me.

### Acceptance Criteria

- [ ] Add a ScrollToTop button that smoothly moves to the top of the page.
- [ ] It fits with our color theme (see [tailwind.config.ts](https://github.com/danielschuster-muc/potter-db/blob/new-website/frontend/tailwind.config.ts)).
- [ ] It's only visible when needed. 
- [ ] Works also for mobile usage. 

### Additional Details

_No response_

### Screenshots

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by kristenking**
## Summary

Implemented a scroll to top button as per issue requirements. Positioned at the bottom right, it appears once the user scrolls down and smoothly takes them to the top when clicked. The icon comes from react-icons. Used React hooks to handle the button's visibility based on the page's scroll position. The button styling is done with Tailwind CSS to ensure it matches the website's color theme.

Changes:

1. Created ScrollToTopButton component.
2. Added ScrollToTopButton to the general layout component.

Testing:

Checked button visibility and functionality on various pages and on mobile.

## Related Issues

Fixes #787 

## Checklist

- [x] This pull request has a meaningful title and description.
- [x] I have read and followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).
- [x] My code follows the conventions and coding style of this project.

# Screenshots (if applicable)

image
***
image
***
image

### CODE REVIEW

**Review by danielschuster-muc — CHANGES_REQUESTED** [review]
Codewise it looks pretty good. 
Could you please check the tab-size (we use 2 instead of 4). Maybe you can just run `npm run lint`?

**Comment by kristenking** [comment]
Thank you for the review @danielschuster-muc . Ran `npm run lint` and pushed the changes. Let me know if anything else needs adjusting.

**Review by danielschuster-muc — APPROVED** [review]
Looks good now.

**Comment by kristenking** [comment]
Thanks for approval @danielschuster-muc . I will wait till it is merged then :)

**Pull request merged**
