### PR TITLE
Update and Design logo

### PR DESCRIPTION
**Pull request by umeshchavda05**
- [X] I have read and agree to the [Code of Conduct](https://github.com/danielschuster-muc/potter-db/blob/master/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).

## Pull Request Type

- [X] New feature (either for website or api)

## Summary

I've designed a new logo for the website using Canva. The font I've used is from https://www.dafont.com/harry-p.font and is free to use. 
I've added the new logo in the images folder.

### CODE REVIEW

**Comment by umeshchavda05** [comment]
updated_logo

**Comment by danielschuster-muc** [comment]
That logo is really cool! Very nice. 
Can you also create another svg icon with just the bolt, which we can use for the favicon?

**Comment by umeshchavda05** [comment]
I've added the new favicon in the same directory.

**Comment by umeshchavda05** [comment]
> That logo is really cool! Very nice. Can you also create another svg icon with just the bolt, which we can use for the favicon? And the bolt part also seems a bit inconsistent with the logo itself. Maybe you can improve this?

hmm about that maybe if I can make it such that the bolt doesn't have a shadow? would that be better?

**Comment by danielschuster-muc** [comment]
> > That logo is really cool! Very nice. Can you also create another svg icon with just the bolt, which we can use for the favicon? And the bolt part also seems a bit inconsistent with the logo itself. Maybe you can improve this?
> 
> hmm about that maybe if I can make it such that the bolt doesn't have a shadow? would that be better?

Yep, that could be better, maybe you can try this? 

And can you maybe "zoom" into the svg icons, so that it fills the full width and height?

**Comment by umeshchavda05** [comment]
> > > That logo is really cool! Very nice. Can you also create another svg icon with just the bolt, which we can use for the favicon? And the bolt part also seems a bit inconsistent with the logo itself. Maybe you can improve this?
> > 
> > 
> > hmm about that maybe if I can make it such that the bolt doesn't have a shadow? would that be better?
> 
> Yep, that could be better, maybe you can try this?
> 
> And can you maybe "zoom" into the svg icons, so that it fills the full width and height?

how about this @danielschuster-muc. I've zoomed it in and removed the shadow.
cropped_icon

**Comment by umeshchavda05** [comment]
I've also added the bolt for the favicon.
cropped_favicon

**Comment by danielschuster-muc** [comment]
Yep, that fits the style of the text much better!

**Comment by umeshchavda05** [comment]
> Yep, that fits the style of the text much better!

great can you merge it then?

**Review by danielschuster-muc — CHANGES_REQUESTED** [review]
Can you please delete `updated_favicon.svg` and `updated_logo.svg`?
And make the `cropped_favicon.svg` a square, rename it to ´icon.svg´ and move it to the root directory? 
And could you also rename the `cropped_icon` to `logo.svg` and move it to the root directory, too? 
The style of the new logo is really amazing and much appreciated!

**Comment by umeshchavda05** [comment]
@danielschuster-muc done. Please take a look.

**Review by danielschuster-muc — APPROVED** [review]
Looks good, thank you for your contribution!

**Pull request merged**
