### PR TITLE
Improve Icon for missing image 

### PR DESCRIPTION
**Pull request by RCNOverwatcher**
- [x] I have read and agree to the [Code of Conduct](https://github.com/danielschuster-muc/potter-db/blob/master/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).

## Pull Request Type

- [x] Other

## Summary

New missing image for the Feature Request: Improve Icon for missing image #184

### CODE REVIEW

**Comment by danielschuster-muc** [comment]
Just out of curiosity as I don't want any legal complains, did you make the image yourself or did you took any references from anywhere (if yes, can we freely use it)?

**Comment by RCNOverwatcher** [comment]
I used a template from a free clipart website, inverted the colours and flipped it in photoshop. The website it came from is free for use but even if it wasn't, i believe the alterations i made should stop any sort of copyright infringment.

**Comment by danielschuster-muc** [comment]
> I used a template from a free clipart website, inverted the colours and flipped it in photoshop. The website it came from is free for use but even if it wasn't, i believe the alterations i made should stop any sort of copyright infringment.

Ok, that sounds good, can you send me the link to the website, just for reference.

**Comment by RCNOverwatcher** [comment]
http://getdrawings.com/

**Comment by RCNOverwatcher** [comment]
I'm pretty sure that this website isn't the only website hosting this image by the way, it's just the one i found it on.

**Comment by RCNOverwatcher** [comment]
On second thoughts, I'll just switch the background colour quickly to match the website

**Comment by RCNOverwatcher** [comment]
This should blend with the background colour to look more seamless

**Comment by danielschuster-muc** [comment]
Ok, so the image seems to be this one: http://getdrawings.com/get-silhouette#witch-on-broom-silhouette-5.jpg
It is licensed under CC BY-NC 4.0 Licence. That means we must credit the image appropiately (I will add a link to for all images we use). With this we should be safe from copyright infringments.

**Comment by RCNOverwatcher** [comment]
My original image didn't have the moon in it so it seems like there are a lot of different images containing the same design out there. I [reverse image searched it on tineye](https://tineye.com/search/b0d6e8359e437c7484f2d22d54b60d94fed61151) and there are a lot of matches.

**Comment by danielschuster-muc** [comment]
Do you have a direct link to the image you used? If you can't find it, maybe it's still available in your search history?

**Comment by RCNOverwatcher** [comment]
[Found it](http://getdrawings.com/get-silhouette#halloween-witch-silhouette-templates-28.jpg)

Same license as you mentioned before so this doesn't change much. However as I said before, this is likely not the original source as there are commercialized t-shirts and merchandise with this clipart on. If I had to guess I would say that this is likely a reupload of a free to use image from somewhere else on the internet.

**Comment by RCNOverwatcher** [comment]
If you want to be on the safe side, I would just say put the attribution link in there just in case.

**Comment by danielschuster-muc** [comment]
Great, thank you!
Yes, this is definitely a broadly used image. 

> If you want to be on the safe side, I would just say put the attribution link in there just in case.
Yep, I will add an attribution link for it.

**Comment by danielschuster-muc** [comment]
#193 adds this attribution file, maybe you want to have a look at it. Afterwards I will merge your pr.

**Comment by RCNOverwatcher** [comment]
Just updated the image one last time to match the background correctly*

**Comment by RCNOverwatcher** [comment]
> #193 adds this attribution file, maybe you want to have a look at it. Afterwards I will merge your pr.

All looks good :)

**Pull request merged**
